### PR TITLE
Disallow muzzle flash if viewmodel is hidden

### LINKED ISSUE #996: Muzzle flashes show when viewmodels are off
**Describe the bug**
Muzzle flashes show for the pistol with `r_drawviewmodels 0`. No other weapon use muzzle flashes to my knowledge.

**To Reproduce**
1. Go into game
2. `r_drawviewmodel 0`
3. `give_weapon weapon_momentum_pistol`
4. Shoot a bunch, see muzzle flashes

**Expected behavior**
Muzzle flash should never show when viewmodels are off.

**Screenshots**
image

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

### PR DESCRIPTION
**Pull request by ijre**
Closes #996 

This PR fixes the issue of muzzle flashes showing while the viewmodel is hidden for the pistol

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/c_baseanimating.cpp [hunk 1]
```diff
@@ -3610,6 +3610,10 @@ void C_BaseAnimating::DoAnimationEvents( CStudioHdr *pStudioHdr )
 //-----------------------------------------------------------------------------
 bool C_BaseAnimating::DispatchMuzzleEffect( const char *options, bool isFirstPerson )
 {
+	static ConVarRef r_drawviewmodel("r_drawviewmodel");
```
Comment (braem) [inline mp/src/game/client/c_baseanimating.cpp:3613]: Instead of having a static `ConVarRef` you can extern this cvar as it is included. Eg. `extern ConVar r_drawviewmodel`.

**Review by braem — CHANGES_REQUESTED** [review]

File: mp/src/game/client/c_baseanimating.cpp [hunk 2]
```diff
@@ -3610,6 +3610,10 @@ void C_BaseAnimating::DoAnimationEvents( CStudioHdr *pStudioHdr )
 //-----------------------------------------------------------------------------
 bool C_BaseAnimating::DispatchMuzzleEffect( const char *options, bool isFirstPerson )
 {
+	extern ConVar r_drawviewmodel;
```
Comment (braem) [inline mp/src/game/client/c_baseanimating.cpp:3613]: Should be outside of the function, by the `ConVar` definitions.

**Review by braem — CHANGES_REQUESTED** [review]

**Review by braem — APPROVED** [review]

File: mp/src/game/client/c_baseanimating.cpp [hunk 3]
```diff
@@ -3610,6 +3611,9 @@ void C_BaseAnimating::DoAnimationEvents( CStudioHdr *pStudioHdr )
 //-----------------------------------------------------------------------------
 bool C_BaseAnimating::DispatchMuzzleEffect( const char *options, bool isFirstPerson )
 {
+	if (!r_drawviewmodel.GetBool())
```
Comment (Gocnak) [inline mp/src/game/client/c_baseanimating.cpp:3614]: Should this also check if `isFirstPerson`?

**Review by Gocnak — CHANGES_REQUESTED** [review]

File: mp/src/game/client/c_baseanimating.cpp (hunk 3 above)
Comment (ijre) [reply mp/src/game/client/c_baseanimating.cpp:3614]: Yeah, definitely, as "isFirstPerson" relates to whether or not it's the NPC or the player; fixing that right now

**Review by Gocnak — APPROVED** [review]
