### PR TITLE
Filter run comparison by track

### LINKED ISSUE #647: Comparisons panel does not properly filter by track
**Describe the bug**
The comparisons logic currently just uses the fastest replay found for the map and does not filter based on your current track, leading to your splits and panel improperly comparing and displaying incorrect info.

**To Reproduce**
Load a map with a bonus track.
`mom_restart <bonus num>` to the bonus track
Do a run, finish it faster than the main track would take, make sure the replay saved!
`mom_restart 0` back to the main track
Do a run, notice comparisons panel uses bonus track PB

You can also see it when restarting the map, it persists as long as you have the bonus run. A solution is to delete it, but:

**Expected behavior**
We should for now filter by track at the very least.

**Desktop (please complete the following information):**
 - OS: Windows

### PR DESCRIPTION
**Pull request by cdennis5**
Closes #647

MomUtil::GetRunComparison and subsequently MomUtil::GetBestTime now compare against a given track number when looking up runs. Runs that are not on the same track as the current player are ignored.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/ui/HUD/hud_comparisons.cpp [hunk 1]
```diff
@@ -157,12 +157,13 @@ void C_RunComparisons::LoadComparisons()
 
         const float tickRate = pRunData->m_flTickRate;
         const int runFlags = pRunData->m_iRunFlags;
+        const int currentTrack = pRunData->m_iCurrentTrack;
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/HUD/hud_comparisons.cpp:160]: You can remove this and instead just call the `pRunData->m_iCurrentTrack` below

File: mp/src/game/shared/momentum/util/mom_util.cpp [hunk 2]
```diff
@@ -380,7 +380,7 @@ CMomReplayBase *MomUtil::GetBestTime(const char *szMapName, float tickrate, uint
             CMomReplayBase *pBase = g_ReplayFactory.LoadReplayFile(pReplayPath, false);
             assert(pBase != nullptr);
                 
-            if (CheckReplayB(pFastest, pBase, tickrate, flags))
+            if (pBase->GetTrackNumber() == trackNumber && CheckReplayB(pFastest, pBase, tickrate, flags))
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/util/mom_util.cpp:383]: Do this inside `CheckReplayB` instead.
