### PR TITLE
Fixed map finished panel not being closable when replay file can't be written

### LINKED ISSUE #793: Map finished panel soft locks when a replay file can't be written
**Describe the bug**
If the game can't write a demo to a file at the end of a map run, trying to replay the demo causes all the buttons on the panel to stop functioning.

**To Reproduce**
1. Open Momentum Mod
2. Delete or rename the replays folder
3. Finish a run
4. Press the Play Replay button

**Expected behavior**
The buttons on the menu should continue to function, and the replay button should maybe play the demo still if it's in memory (?)

**Desktop (please complete the following information):**
 - OS: Windows

### PR DESCRIPTION
**Pull request by braem**
Closes #793 - Added the issue to the 0.8.5 release as well since it's hud related. Apologies if I shouldn't have done this.

Fixed this issue by fixing up some relevant code.

The `replay_save` event was not fired when the replay file was unable to be written to, despite it having a boolean `save` field that specifies whether it succeeded or not. This means every time `replay_save` is fired it's `save` field is `true`.
Every catching of this event checks whether `save` is `true`:
- `mom_run_poster.cpp`
- `hud_comparisons.cpp`
- `hud_mapfinished.cpp`
- `ClientTimesDisplay.cpp`

So having it fire regardless of whether saving succeeded has no repercussions.

Made the replay save button on the map finished panel disabled until the `replay_save` event is fired with a `save` field of `true`. Without this, clicking the play replay button when the replay fails to save prevents the panel from closing. This shouldn't be clickable anyways until the replay is saved.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp [hunk 1]
```diff
@@ -156,6 +157,7 @@ void CHudMapFinishedDialog::LevelShutdown()
     m_pRunData = nullptr;
     m_bIsGhost = false;
     m_bCanClose = false;
+    m_pPlayReplayButton->SetEnabled(false);
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp:160]: Is this one necessary? Wouldn't the one in Reset catch the use case of this?

File: mp/src/game/server/momentum/mom_replay_system.cpp [hunk 2]
```diff
@@ -144,20 +144,20 @@ void CMomentumReplaySystem::FinishRecording()
...
+    {
+        pReplaySavedEvent->SetBool("save", bStoredReplay);
+        pReplaySavedEvent->SetString("filepath", newRecordingPath);
+        pReplaySavedEvent->SetInt("time", static_cast<int>(m_pRecordingReplay->GetRunTime() * 1000.0f));
+        gameeventmanager->FireEvent(pReplaySavedEvent);
+    }
 
+    if (bStoredReplay)
+    {
+        Log("Recording Stopped! Ticks: %i\n", m_pRecordingReplay->GetFrameCount());
```
Comment (Gocnak) [inline mp/src/game/server/momentum/mom_replay_system.cpp:160]: While we're here can we implement the simple suggestion of also printing out the run time to console? Should just be a call to `MomUtil::FormatTime` with the recording replay's *run time* (not frame count)

**Comment by braem** [comment]
Removed that useless call in `LevelShutdown()`

Added the time printout.
image
