### PR TITLE
Make ClientTimesDisplay static

### LINKED ISSUE #1135: Game crash when changing resolution on a map (Related to async replays)
**Describe the bug**
When changing the window resolution while on a map with ~50+ local replays, the game will crash with the following stack:
```
CMomReplayBase** CopyConstruct<CMomReplayBase*>(CMomReplayBase**, CMomReplayBase* const&) platform.h:1287
CUtlVector<CMomReplayBase*, CUtlMemory<CMomReplayBase*, int> >::InsertBefore(int, CMomReplayBase* const&) utlvector.h:954
CUtlVector<CMomReplayBase*, CUtlMemory<CMomReplayBase*, int> >::AddToTail(CMomReplayBase* const&) utlvector.h:932
CMomReplayFactory::FilesystemCallback(FileAsyncRequest_t const&, int, FSAsyncStatus_t) mom_replay_factory.cpp:237
CMomReplayFactory::FilesystemCallbackForward(FileAsyncRequest_t const&, int, FSAsyncStatus_t) mom_replay_factory.cpp:204
<unknown> 0x00000000f6ba8435
<unknown> 0x00000000f6ba65c0
<unknown> 0x00000000f6ba7498
<unknown> 0x00000000f6bab629
<unknown> 0x00000000f785effa
CThread::ThreadProc(void*) 0x00000000f7f48880
start_thread 0x00000000f7f051d4
__GI___clone 0x00000000f7e1b5e6
```

**To Reproduce**
- Join a map where you have 50+ local replays
- Change resolution / Switch fullscreen mode

**Expected behavior**
No crash

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: **develop**

**Additional context**
I'm adding this issue for record-keeping and because I have absolutely no clue what is going on but I'll also look into this myself, of course.

The callback seems to complete for 42-48 replays without a problem but for some reason, at that point, it fails when allocating the pointer. IMO reloading the replay files when changing resolution doesn't make much sense anyways but that's just a consequence of the panel being destroyed. And even then, I'm not really sure why it suddenly fails. Is there some random memory shortage while resizing or a race condition regarding the IO thread?

If I find no other solution, then I'll probably just open a PR to move leaderboard replay loading back to initial panel open instead of LevelInit before 0.8.7.

### PR DESCRIPTION
**Pull request by bltech**
Closes #1135 and also the discussion on #1061

Turns ClientTimesDisplay into a static panel and makes its update logic much less wasteful. The details are in the commit comment. The only thing I'm really unhappy with is that I couldn't name the init function Init() like with the other static panels because CBaseGameSystem, which is a superclass of the panel, already provides Init().

I also looked into whether it was possible to stop the request focus spam in the console without directly editing panel.cpp but found no good way to do it and declaring it a console-style panel doesn't make sense either.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp [hunk 1]
```diff
@@ -209,16 +214,15 @@ void CClientTimesDisplay::FireGameEvent(IGameEvent *event)
     }
 }
 
-bool CClientTimesDisplay::NeedsUpdate() { return (m_flNextUpdateTime < gpGlobals->curtime); }
+inline bool CClientTimesDisplay::NeedsUpdate() { return (m_flNextUpdateTime < gpGlobals->curtime); }
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:217]: Can just be in the `TryUpdate` function directly.

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp [hunk 2]
```diff
@@ -176,7 +181,7 @@ void CClientTimesDisplay::Close()
     SetMouseInputEnabled(false);
     SetKeyBoardInputEnabled(false);
 
-    g_pClientMode->GetViewportAnimationController()->StartAnimationSequence(GetParent(), "LeaderboardsBgFocusLost");
+    g_pClientMode->GetViewportAnimationController()->StartAnimationSequence(this, "LeaderboardsBgFocusLost");
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:184]: Not sure on this change, shouldn't this be `StartAnimationSequenceForPanel` ?

File: mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp [hunk 3]
```diff
@@ -323,6 +322,9 @@ void CLeaderboardsTimes::SetPlaceColors(SectionedListPanel* panel, TimeType_t ty
     if (itemCount == 0)
         return;
 
+    // We need to force the panel to resort its items now
+    m_pLocalLeaderboards->InvalidateLayout(true, false);
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp:326]: `false` isn't needed for the second param, they both default to false.

```suggestion
    m_pLocalLeaderboards->InvalidateLayout(true);
```

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp [hunk 4]
```diff
@@ -133,12 +133,17 @@ void CClientTimesDisplay::ShowPanel(bool bShow)
...
     if (bShow)
     {
-        Reset(true);
+        Update(true, true);
         SetVisible(true);
         MoveToFront();
         RequestFocus();
 
-        const auto pSpecUI = m_pViewPort->FindPanelByName(PANEL_SPECGUI);
+        const auto pViewPort = dynamic_cast<IViewPort *>(g_pClientMode->GetViewport());
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:141]: Cast is not needed.

File: mp/src/game/client/momentum/clientmode_mom_normal.cpp [hunk 5]
```diff
@@ -167,11 +162,11 @@ int ClientModeMOMNormal::HudElementKeyInput(int down, ButtonCode_t keynum, const
     }
 
     // Detach the mouse if the user right-clicked while the leaderboards are open
-    if (m_pLeaderboards && m_pLeaderboards->IsVisible())
+    if (g_pClientTimes && g_pClientTimes->IsVisible())
```
Comment (Gocnak) [inline mp/src/game/client/momentum/clientmode_mom_normal.cpp:165]: `g_pClientTimes` should never be null here.

```suggestion
    if (g_pClientTimes->IsVisible())
```

**Review by Gocnak — CHANGES_REQUESTED** [review]

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp (hunk 4 above)
Comment (bltech) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:141]: How else would I do it though? GetViewport() only returns a Panel* and I need FindPanelByName from IViewPort

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp [hunk 6]
```diff
@@ -209,16 +214,15 @@ void CClientTimesDisplay::FireGameEvent(IGameEvent *event)
...
-bool CClientTimesDisplay::NeedsUpdate() { return (m_flNextUpdateTime < gpGlobals->curtime); }
+inline bool CClientTimesDisplay::NeedsUpdate() { return (m_flNextUpdateTime < gpGlobals->curtime); }
 
 //-----------------------------------------------------------------------------
 // Purpose: Recalculate the internal scoreboard data
 //-----------------------------------------------------------------------------
-void CClientTimesDisplay::Update() { Update(false); }
 
-void CClientTimesDisplay::Update(bool pFullUpdate)
+void CClientTimesDisplay::Update(bool pFullUpdate, bool bUpdateNow)
```
[the remark this answers is not in the document]
Comment (bltech) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:223]: I was trying to imitate the style of InvalidateLayout(bool, bool) but I can see how it's better to tear it apart for new code.

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp (hunk 2 above)
Comment (bltech) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:184]: Hmm, I tried `GetAnimationController()->StartAnimationSequenceForPanel` but that failed spectacularly by extending the panel to the full screen size and then throwing a SIGFPE. 
Is the current way wrong because it's not a Viewport Panel anymore?

Comment (Gocnak) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:184]: Huh, okay. I thought the animation was doing something in this class (CClientTimesDisplay) but it looks like this would be correct. 👍

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp (hunk 4 above)
Comment (Gocnak) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:141]: Oh damn my bad I thought it returned the CBaseViewport lol. The cast is fine then, or you can change the method to return an IViewport pointer.

Comment (SCell555) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:141]: That also won't work. Nearly every usage of this uses it for the Panel pointer

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp (hunk 2 above)
Comment (bltech) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:184]: I guess I can still use `GetAnimationController()->StartAnimationSequence(...)` to skip that indirection though

Comment (Gocnak) [reply mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:184]: So long as the animation still works with this change, it's okay. I was just curious if the animation broke at all when doing this.

**Comment by bltech** [comment]
I'm almost ready for second review however during testing, I came across a weird bug that happens when resizing while hiving had a non-local leaderboard panel open:
https://streamable.com/a9rtjd

m_pCurrentLeaderboards is still correctly set to the global panel and that causes the place colors of the local panel not to show up. But I don't understand why it shows the local panel after res change with the buttons also somehow changing state accordingly.

Do you, by chance, have any idea what VGUI mechanism might cause this? From what I found, the only time the buttons' state changes is in OnCommand of ClientTimesDisplay and that doesn't get called on res change.

**Comment by Gocnak** [comment]
I think if people are changing resolution the leaderboards panel should just close itself.

**Comment by bltech** [comment]
Ah I think I was a bit vague, what I meant by open is that the last panel that was opened was one of the global times panel. Of course you can't really change resolution while it's open.

**Comment by Gocnak** [comment]
Ah okay I understand now. Changing resolution reloads the res files and there might be something making an assumption. Previously the entire panel was destroyed. I think something to try is re-evaluating the buttons after changing resolution perhaps.

**Comment by bltech** [comment]
Of course it's the controls file, I completely forgot that visibility etc. is set there, thanks! W.r.t. reevaluating this, should the focus be to respect the res file and set visibility to whatever's specified there or keep what was last displayed?

**Comment by Gocnak** [comment]
Yeah I think visibility can be forced off ("0") in there and instead be evaluated in code.

**Comment by bltech** [comment]
OK so apart from the code review changes, to fix two bugs that I noticed, I
- parented the leaderboards to clientdll so that you can't hold tab and then press escape to make the leaderboards shine through the main menu
- moved the panel switch logic to its own function to fix control reload. This ended up a lot more boilerplate-y and verbose than I really wanted to but the old code was very optimized to its usecase and made lots of assumptions. This way, at least the panel would be future-proofed if e.g. a rivals leaderboard/steam group/whatever were to be added

**Review by Gocnak — APPROVED** [review]
