### PR TITLE
Hide scoreboard and lobby panels during credits

### LINKED ISSUE #559: Leaderboard menu still accessible when in credits
**Describe the bug**
You are able to open the tab/leaderboard menu in the credits.

**Screenshots**
download

**Additional context**
None, just a minor bug :)

### PR DESCRIPTION
**Pull request by cdennis5**
Closes #559

During the credits sequence, hide the leaderboard and lobby panels if they're visible.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/hl2/hud_credits.cpp [hunk 1]
```diff
@@ -743,4 +748,23 @@ void CHudCredits::MsgFunc_LogoTimeMsg(bf_read &msg)
...
-}
\ No newline at end of file
+}
+
+void CHudCredits::HideScoreboardAndLobby()
+{
+    if (gViewPortInterface)
+    {
+        IViewPortPanel *showtimesPanel = gViewPortInterface->FindPanelByName(PANEL_TIMES);
+        IViewPortPanel *showlobbyPanel = gViewPortInterface->FindPanelByName(PANEL_LOBBY_MEMBERS);
```
Comment (Gocnak) [inline mp/src/game/client/hl2/hud_credits.cpp:758]: Finding panel by name should not be done every frame. In fact, on line 55 in this file, there's a `g_bRollingCredits` bool that's globally accessible from anywhere in the client DLL. So, theoretically, you can go to both of these panels, and in their `SetVisible` methods, check if the credits are rolling and if so, just return without setting visible (still allow hiding the panels though).

File: mp/src/game/client/hl2/hud_credits.cpp [hunk 2]
```diff
@@ -17,6 +18,7 @@
 #include "iclientmode.h"
 #include "in_buttons.h"
 #include "input.h"
+#include "momentum/mom_shareddefs.h"
```
Comment (Gocnak) [inline mp/src/game/client/hl2/hud_credits.cpp:21]: You can remove these two includes, these are no longer used.

File: mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp [hunk 3]
```diff
@@ -173,6 +175,9 @@ void CClientTimesDisplay::ShowPanel(bool bShow)
     if (BaseClass::IsVisible() == bShow)
         return;
 
+    if (g_bRollingCredits)
+        return;
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/leaderboards/ClientTimesDisplay.cpp:179]: Move this to just inside the `if (bShow)` check below (before the `Reset(true);`); we want the panels to still be closeable if in credits.

File: mp/src/game/client/momentum/ui/lobby/LobbyMembersPanel.cpp [hunk 4]
```diff
@@ -294,6 +296,9 @@ void LobbyMembersPanel::ShowPanel(bool bShow)
     if (BaseClass::IsVisible() == bShow)
         return;
 
+    if (g_bRollingCredits)
+        return;
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/lobby/LobbyMembersPanel.cpp:300]: Same here, move this to inside that `if (bShow)` check.

File: mp/src/materialsystem/stdshaders/momentum_dx9_30.txt [hunk 5]
```diff
@@ -1,30 +1,27 @@
...
+SDK_flashlight_ps2x.fxc
+SDK_lightmappedgeneric_flashlight_vs20.fxc
+//SDK_lightmappedgeneric_ps20b.fxc
+SDK_lightmappedgeneric_ps2x.fxc
+//SDK_lightmappedgeneric_filter0_ps30.fxc
+//SDK_lightmappedgeneric_filter1_ps30.fxc
+//SDK_lightmappedgeneric_filter2_ps30.fxc
+SDK_lightmappedgeneric_vs20.fxc
+
+//decalmodulate_ps2x.fxc
```
Comment (Gocnak) [inline mp/src/materialsystem/stdshaders/momentum_dx9_30.txt:27]: Ah, you ran into this bug. This is actually a really bizarre artifact of the repo that we aren't really sure how to prevent. But you're going to want to reset back and follow another type of fix:

1. Do the things I suggested above, but do not commit it.
2. Instead, do `git reset HEAD~3` to bring your branch back 3 commits ago. This will bring all your changes back for staging and committing.
3. Re-create your initial feature commit as you had it, **DO NOT COMMIT THE `momentum_dx9_30.txt` AND `momentum_dx9_20b.txt` FILES!**
4. With your actual feature work in a commit (**AND NOT PUSHED**), and these shader files in staging (**NOT COMMITTED**), you can now do the following to fix this weird bug:
```
git rm .gitattributes
git add -A
```
And discard the change to the gitattributes file.

5. These two files should be gone. If so, you can now `git push --force` to update this branch, cleaning it from these files (as well as the extra commits you did before!)

Any doubts about this, just PM me.
