### PR TITLE
Stopped stickybomb from firing before releasing mouse1 when charge is disabled

### LINKED ISSUE #655: Stickybomb is forced out of stickylauncher when charging is not enabled
**Describe the bug**
When charging is not enabled (ie. in the start zone), the stickybomb still fires if `+attack` is held down long enough. 

**To Reproduce**

1. Enter start zone with stickylauncher active.
2. Hold whatever is bound to `+attack`, most likely `mouse1`
3. Stickybomb will eventually fire without needing to release `+attack`.

**Expected behavior**
If charge is disabled, stickybomb should not fire until `+attack` is released.

**Desktop (please complete the following information):**
 - OS: Windows

### PR DESCRIPTION
**Pull request by braem**
Closes #655 

Holding down `+attack` when charge is disabled will no longer fire a sticky before it is released. That is, apart from their velocity, stickybombs are acting as if they are charged when charging is disabled.
Added a check to see if charging is enabled in the spot that fires a sticky when it's fully charged.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by braem** [comment]
> 
> 
> Make sure to cancel the charge sound when charging and entering start zone in this branch.

Did this and added another sound that plays when player is charging & then charging is disabled.
This sound sounds very similar to the sticky deny sound though so it might be worth hunting for a different sound.

File: mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp [hunk 1]
```diff
@@ -275,6 +283,14 @@ float CMomentumStickybombLauncher::CalculateProjectileSpeed(float flProgress)
                            MOM_STICKYBOMB_MIN_CHARGE_VEL, MOM_STICKYBOMB_MAX_CHARGE_VEL);
 }
 
+void CMomentumStickybombLauncher::StopChargeSound() 
+{
+    if (m_flChargeBeginTime > 0) // stop only if charging
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp:288]: I think regardless of whether it was charging, you'll want to `StopWeaponSound(GetWeaponSound("charge"));` as well.

File: mp/game/momentum/scripts/game_sounds_momentum_weapons.txt [hunk 2]
```diff
@@ -148,6 +148,14 @@
     "wave"		"weapons/stickybomblauncher_charge_up.wav"
 }
 
+"StickybombLauncher.ChargeStop"
+{
+    "channel"	"CHAN_WEAPON"
```
Comment (Gocnak) [inline mp/game/momentum/scripts/game_sounds_momentum_weapons.txt:153]: Use `"CHAN_AUTO"` instead.

**Comment by braem** [comment]
Amended the commit with these changes, though:
The explicit call to stop the charge sound isn't used when a sticky is shot, rather it is leveraging the fact that they're on the same channel. Would you like an explicit `StopWeaponSound(GetWeaponSound("charge"))` call before firing a sticky as well? Would safeguard against the event they are on separate channels but I doubt that will ever occur.

**Comment by Gocnak** [comment]
> The explicit call to stop the charge sound isn't used when a sticky is shot, 

Actually I do it in my sticky fixes PR (#654) because it's important to stop the sound, this script can be edited by players and they'll report it as a bug.

> rather it is leveraging the fact that they're on the same channel. Would you like an explicit `StopWeaponSound(GetWeaponSound("charge"))` call before firing a sticky as well?

Right, I don't want to rely on the channel thing. It's good to be explicit, plus it's confusing code having a method "StopChargeSound" not *actually* stop the charge sound.

**Comment by braem** [comment]
> 
> Just do it for the StopChargeSound method, I got the sticky firing case covered in my PR.

Sounds good :) the work is done & rebased.

File: mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp [hunk 3]
```diff
@@ -278,6 +286,15 @@ float CMomentumStickybombLauncher::CalculateProjectileSpeed(float flProgress)
...
+    {
+        StopWeaponSound(GetWeaponSound("charge"));
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/weapon/weapon_mom_stickybomblauncher.cpp:293]: I was saying regardless of charge time, you can stop the sound. This can move out of the if check.

File: mp/src/game/server/momentum/mom_player.cpp [hunk 4]
```diff
@@ -910,6 +910,7 @@ void CMomentumPlayer::OnZoneEnter(CTriggerZone *pTrigger)
                     const auto pLauncher = static_cast<CMomentumStickybombLauncher *> (GetWeapon(WEAPON_STICKYLAUNCHER));
                     if (pLauncher)
                     {
+                        pLauncher->StopChargeSound();
```
Comment (Gocnak) [inline mp/src/game/server/momentum/mom_player.cpp:913]: This should be done in the `SetChargeEnabled` method since it is only being ran bundled with it, making it a loose dependency. I'd rather only have to call `SetChargeEnabled(false)` instead of having to remember to also call `StopChargeSound` as well, if that makes sense.

Comment (braem) [reply mp/src/game/server/momentum/mom_player.cpp:913]: Had it there before but opted for a cleaner `SetChargeEnabled` function. Will change it back.
