### PR TITLE
Fix player getting stuck when closing settings panel

### LINKED ISSUE #850: Hitting escape while in game and in the settings panel freezes the player
**Describe the bug**
While in game, opening the settings panel and hitting escape (to close it) actually resumes the game and does *not* close the panel, making the player stuck until they press escape again.

**To Reproduce**

- Go in game
- Open settings panel
- Interact with it?
- Press "escape" instead of manually closing the settings panel
- Notice the game goes back "in game"
- You cannot move
- Pressing escape brings back up the gameui, with the settings panel still open

**Expected behavior**
The settings panel should follow the chat dialog's steps and [prevent/allow gameui escape using the concommands](https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/hud_basechat.cpp#L910).

### PR DESCRIPTION
**Pull request by braem**
Closes #850 

This seemed to happen only when a combobox had a menu open while the player hit escape to close the settings. The menu on the comboboxes eat escape key input, causing the `OnClose()` for the settings panel to not execute. Added a baseclass call there to prevent it from eating input.

Tested this with the other panels (zone menu & map selector) and they act the same with or without the change.

Also added the prevent/allow escape to show on the settings panel as I figure it should be there, though it change doesn't change anything. Without the menu input fix, it softlocks the game (cannot press escape to show menu nor move nor open console). Can drop that commit if we don't really need.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/ui/SettingsPanel/MomentumSettingsDialog.cpp [hunk 1]
```diff
@@ -245,4 +247,6 @@ CON_COMMAND_F(mom_settings_show, "Shows the settings panel.\n", FCVAR_CLIENTCMD_
     }
 
     g_pSettingsDialog->DoModal();
+
+    engine->ClientCmd_Unrestricted("gameui_preventescapetoshow\n");
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/SettingsPanel/MomentumSettingsDialog.cpp:251]: As per your description, if this wasn't the fix to it this commit can be dropped, yeah. The chat panel does it so that escape closes chat and doesn't open the menu. The settings menu being opened already means the menu is open, so this command was just a red herring.
