### PR TITLE
Fix constant menu blur while in tools mode

### LINKED ISSUE #959: Tools mode and menu background blur
**Describe the bug**
Running the game in tools mode and entering a map will make the game render the viewport blurred, as if the menu was open

**To Reproduce**

1. Run the game with `-tools`
2. Enter any map
3. ???

**Expected behavior**
Running the game in tools mode should not cause viewport blurring, even when the input is being eaten by the tools and not the game

**Screenshots**
image
Tools mode: Game has fullscreen + input

image
Tools mode: Tools have fullscreen + input

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: enhance/weapon-viewmodels (rebased 7 days ago, 13/09/20)

**Additional context**
The game is also running with `-forceallmips -nop4` but I do not beileve these have any impact on this issue

### PR DESCRIPTION
**Pull request by xen-000**
Closes #959

Opening the menu and/or console is still broken in tools mode and I imagine that will require engine to fix.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/ui/gameui/mainmenu/MainMenu.cpp [hunk 1]
```diff
@@ -309,6 +315,8 @@ void MainMenu::DrawMainMenu()
         }
     }
 
+    SetPostProcessParams(&m_PostProcessParameters, true);
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/gameui/mainmenu/MainMenu.cpp:318]: Should this move a few lines down to inside the `IsInLevel` check? That's where it was previously.

Comment (xen-000) [reply mp/src/game/client/momentum/ui/gameui/mainmenu/MainMenu.cpp:318]: I figured that won't be necessary because we're moving to model panel for the menu background, but better safe than sorry I suppose.

**Review by Gocnak — APPROVED** [review]
