### PR TITLE
Normalize entities' angles when they hit the angle limit

### LINKED ISSUE #383: Main menu map crashes after a long time
Reported by Flipybitz

He hits this assert due to the rotation going on for so long:
image

Solution is to just check when the angle becomes unreasonable and correct it to the original angle.

### PR DESCRIPTION
**Pull request by xen-000**
Closes #383 

Previously, whenever an entity's angles hit ±360000 degrees on any axis (usually func_rotating), it would refuse to update its angles any further which froze the entity while showing constant warnings. Instead, the angles are now normalized to within ±180 degrees whenever the limit is hit.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/server/baseentity.cpp [hunk 1]
```diff
@@ -5932,22 +5932,12 @@ void CBaseEntity::SetLocalOrigin( const Vector& origin )
...
 	if ( !IsEntityQAngleReasonable( angles ) )
 	{
-		if ( CheckEmitReasonablePhysicsSpew() )
-		{
-			Warning( "Bad SetLocalAngles(%f,%f,%f) on %s\n", angles.x, angles.y, angles.z, GetDebugName() );
-		}
-		AssertMsg( false, "Bad SetLocalAngles(%f,%f,%f) on %s\n", angles.x, angles.y, angles.z, GetDebugName() );
+		QAngle angleNormalize(AngleNormalize(angles.x), AngleNormalize(angles.y), AngleNormalize(angles.z));
+		SetLocalAngles(angleNormalize);
 		return;
```
Comment (Gocnak) [inline mp/src/game/server/baseentity.cpp]: It may be better to just set `angles = angleNormalize;` here and instead of returning let the function continue with the new value.
