### PR TITLE
Move localization methods

### LINKED ISSUE #308: Move all LOCALIZE_TOKEN (and other Localization methods) for HUD elements to Reset() function
Since Init() or the constructor is only called once, reloading localization files on the fly will not work unless you restart the game. Moving to Reset() where it gets called every player spawn/map reload is much better for testing localization.

### PR DESCRIPTION
**Pull request by luccapedrini**
Closes #308 

This PR moves localization methods so it's possible to reload localization files without the need to restart the game.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/ui/spectate/mom_replayui.cpp [hunk 1]
```diff
@@ -255,6 +253,8 @@ void C_MOMReplayUI::ShowPanel(bool state)
     if (pSpecUI && pSpecUI->IsVisible() && ipanel()->IsMouseInputEnabled(pSpecUI->GetVPanel()))
         SetMouseInputEnabled(true);
     if (state)
+        FIND_LOCALIZATION(m_pwReplayTime, "#MOM_ReplayTime");
+        FIND_LOCALIZATION(m_pwReplayTimeTick, "#MOM_ReplayTimeTick");
         MoveToFront();
```
Comment (Gocnak) [inline mp/src/game/client/momentum/ui/spectate/mom_replayui.cpp:258]: Wrap these in curlies:

```suggestion
    if (state)
    {
        FIND_LOCALIZATION(m_pwReplayTime, "#MOM_ReplayTime");
        FIND_LOCALIZATION(m_pwReplayTimeTick, "#MOM_ReplayTimeTick");
        MoveToFront();
    }
```
