### PR TITLE
Properly reset run safeguards

### LINKED ISSUE #1068: mom_restart from console breaks run safeguards
**Describe the bug**
Running 'mom_restart' from the console disables the run safeguards that are set.

**To Reproduce**

1) Enable any run safeguard and enter a zoned map, pressing the reset current stage bind works as normal.
2) Run 'mom_restart' from the console and press the reset current stage bind in the map zone.

Video: https://streamable.com/vloj96

**Expected behavior**

The run safeguards should still be in place after restarting the map.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

### PR DESCRIPTION
**Pull request by braem**
Closes #1068 

- Resets all run safeguards when entering start zone
- Resets the `mom_restart_stage` safeguard when entering a stage/checkpoint zone
- Resets the double press safeguard when it is not safeguarded (when it returns false)
  - Actions could happen with no safeguard after they have been safeguarded once as this was not being reset (IE opening chat should always be safeguarded, not failing to be when spammed)

For now, "reset" refers to the double press safeguard's `m_flLastTimePressed`.

Zone entering resets can't happen in their respective `TimerCommand_*` methods because the player can hit those without explicitly restarting. 
Stops the case where: press once, get safeguarded > restart by failing > exit zone > do command again & not get safeguarded.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by braem** [comment]
Aaaaand immediately realize this would be better in `OnZoneExit`, to properly reset when the player starts a run/stage.

File: mp/src/game/shared/momentum/run/mom_run_safeguards.cpp [hunk 1]
```diff
@@ -165,6 +171,27 @@ MomRunSafeguards::MomRunSafeguards()
 #endif
 }
 
+void MomRunSafeguards::Reset()
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/run/mom_run_safeguards.cpp:174]: Should be called `ResetAllSafeguards()`

File: mp/src/game/shared/momentum/run/mom_run_safeguards.cpp [hunk 2]
```diff
@@ -165,6 +171,27 @@ MomRunSafeguards::MomRunSafeguards()
...
+{
+    for (int i = 0; i < RUN_SAFEGUARD_COUNT; i++)
+    {
+        m_pSafeguards[i]->Reset();
+    }
+}
+
+void MomRunSafeguards::Reset(int type)
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/run/mom_run_safeguards.cpp:182]: Should be called `ResetSafeguard()` same with the enum one.

File: mp/src/game/shared/momentum/run/mom_run_safeguards.cpp [hunk 3]
```diff
@@ -136,6 +141,7 @@ bool CRunSafeguard::IsDoublePressSafeguarded()
         return true;
     }
 
+    Reset();
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/run/mom_run_safeguards.cpp:144]: So if I'm reading this correctly, `m_flLastTimePressed` should be set inside the `if (m_bDoublePressSafeguard)` block, so that it is otherwise is reset here.

**Review by Gocnak — CHANGES_REQUESTED** [review]

File: mp/src/game/shared/momentum/run/mom_run_safeguards.cpp (hunk 3 above)
Comment (Gocnak) [reply mp/src/game/shared/momentum/run/mom_run_safeguards.cpp:144]: And now that I read this even more, should the first if block absorb the `if (m_bDoublePressSafeguard)` block?

Comment (Gocnak) [reply mp/src/game/shared/momentum/run/mom_run_safeguards.cpp:144]: You could actually get rid of `m_bDoublePressSafeguard` and just use the time pressed.

**Comment by braem** [comment]
Did the requested changes. The only casualty of removing `m_bDoublePressSafeguard` was that it wasn't hit when starting run right after loading a map, so in the `Reset` method i just subtracted the max double press time.

**Review by Gocnak — APPROVED** [review]
