### PR TITLE
Fixed incorrect sound when landing on slope

### LINKED ISSUE #322: Hitting a slope plays the stepsound of the last surface instead of the slope's surface
May have to see what the order of it is, seems to play the last ground's sound until you "stand" on another ground.

### PR DESCRIPTION
**Pull request by BraxtonDeHate**
Closes #322 

Added a fix to `mom_gamemovement.cpp` which will solve the bug where hitting a slope and losing a large amount of velocity will play the landing sound of the last surface touched. 

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/shared/momentum/mom_gamemovement.cpp [hunk 1]
```diff
@@ -2150,13 +2150,23 @@ int CMomentumGameMovement::TryPlayerMove(Vector *pFirstDest, trace_t *pFirstTrac
...
-    else if (fLateralStoppingAmount > PLAYER_MAX_SAFE_FALL_SPEED)
+    if (fLateralStoppingAmount > PLAYER_MAX_SAFE_FALL_SPEED)
     {
+        // If we are going to play a rough landing, make sure that the player's surface data
+        // is up to date. Otherwise, hitting a surfable slope and triggering this will play
+        // the stepsound of the last walked on surface, as by default the step surface is
+        // only updated for walkable surfaces. Here we are using the last player trace.
+        IPhysicsSurfaceProps *pPhysprops = MoveHelper()->GetSurfaceProps();
+        player->m_surfaceProps = pm.surface.surfaceProps;
+        player->m_pSurfaceData = pPhysprops->GetSurfaceData(player->m_surfaceProps);
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/mom_gamemovement.cpp]: It may not be wise to set the player's surface if they aren't technically standing on it. What about modifying the base class PlayerRoughLandingEffects to take in an optional surface properties pointer and if null just use the player's current surface properties? That way you can pass in this trace's surface for this, but the default can just use the player surface as it normally does.

Comment (BraxtonDeHate) [reply mp/src/game/shared/momentum/mom_gamemovement.cpp]: Good point and I like that solution. Definitely best not to modify state when I don't know everything the state does.

File: mp/src/game/shared/momentum/mom_gamemovement.cpp [hunk 2]
```diff
@@ -2150,16 +2119,18 @@ int CMomentumGameMovement::TryPlayerMove(Vector *pFirstDest, trace_t *pFirstTrac
...
+    // Increase volume for a harder collision.
+    if (fLateralStoppingAmount > PLAYER_MAX_SAFE_FALL_SPEED * 2.0f)
     {
-        fSlamVol = 0.85f;
+      fSlamVol = 1.0f;
     }
 
-    PlayerRoughLandingEffects(fSlamVol);
+    // Use the last traced surface for the landing sound.
+    PlayerRoughLandingEffects(fSlamVol, pm.surface.surfaceProps);
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/mom_gamemovement.cpp]: Since calling this method only does anything if `fSlamVol` is `> 0.0`, you can go back to the logic you had before, and do:

```
if (fLateralStoppingAmount > PLAYER_MAX_SAFE_FALL_SPEED)
{
   float fSlamVol = (fLateralStoppingAmount > PLAYER_MAX_SAFE_FALL_SPEED * 2.0f) ? 1.0f : 0.85f;  
   PlayerRoughLandingEffects(fSlamVol, pm.surface.surfaceProps);
}
```

File: mp/src/game/shared/gamemovement.h [hunk 3]
```diff
@@ -209,7 +209,7 @@ class CGameMovement : public IGameMovement
 
 	virtual void	CheckFalling( void );
 
-	virtual void	PlayerRoughLandingEffects( float fvol );
+	virtual void PlayerRoughLandingEffects(float fvol, short surfacePropsIndex = -1);
```
Comment (Gocnak) [inline mp/src/game/shared/gamemovement.h]: I'd go with:
```suggestion
	virtual void PlayerRoughLandingEffects(float fvol, short surfacePropsIndexOverride = -1);
```

File: mp/src/game/shared/gamemovement.cpp [hunk 4]
```diff
@@ -3931,26 +3931,34 @@ void CGameMovement::CheckFalling( void )
 	player->m_Local.m_flFallVelocity = 0.0f;
 }
 
-void CGameMovement::PlayerRoughLandingEffects( float fvol )
+void CGameMovement::PlayerRoughLandingEffects(float fvol, short surfacePropsIndex)
 {
+	surfacedata_t* surfaceData;
+
 	if ( fvol > 0.0 )
```
Comment (Gocnak) [inline mp/src/game/shared/gamemovement.cpp]: No need to declare the pointer outside of this if block, it only gets used inside of it, and use `pSurfaceData` instead.

File: mp/src/game/shared/gamemovement.cpp [hunk 5]
```diff
@@ -3931,26 +3931,34 @@ void CGameMovement::CheckFalling( void )
...
+		{
+			// Play step sound for specified surface.
+			surfaceData = MoveHelper()->GetSurfaceProps()->GetSurfaceData(surfacePropsIndex);
+
+			// Fallback in case of bad index.
+			if (!surfaceData)
+			{
+				surfaceData = player->m_pSurfaceData;
+			}
+		}
```
Comment (Gocnak) [inline mp/src/game/shared/gamemovement.cpp]: This can be simplified as well:

```cpp
player->m_flStepSoundTime = 400;

surfacedata_t *pSurfaceData = nullptr;
if (surfacePropsIndexOverride != -1)
{
    pSurfaceData = MoveHelper()->GetSurfaceProps()->GetSurfaceData(surfacePropsIndexOverride);
}

if (!pSurfaceData)
{
    pSurfaceData = player->m_pSurfaceData;
}

pPlayer->PlayStepSound( ... );
```

Comments are really not needed; clean code should be very clear as to what it's doing, so if it's not, try to use better naming.

File: mp/src/game/shared/gamemovement.cpp [hunk 6]
```diff
@@ -3931,26 +3931,34 @@ void CGameMovement::CheckFalling( void )
 	player->m_Local.m_flFallVelocity = 0.0f;
 }
 
-void CGameMovement::PlayerRoughLandingEffects( float fvol )
+void CGameMovement::PlayerRoughLandingEffects(float fvol, short surfacePropsIndex)
```
Comment (Gocnak) [inline mp/src/game/shared/gamemovement.cpp]: When there's a default value it's good to put it in an inline comment so people don't have to constantly switch between header and cpp file:

```suggestion
void CGameMovement::PlayerRoughLandingEffects(float fvol, short surfacePropsIndexOverride /*= -1*/)
```

File: mp/src/game/shared/gamemovement.cpp (hunk 4 above)
Comment (BraxtonDeHate) [reply mp/src/game/shared/gamemovement.cpp]: I tried my best to match the convention of the other functions in the file, should I use the momentum guidelines when editing files that came with the SDK?

File: mp/src/game/shared/gamemovement.cpp (hunk 6 above)
Comment (BraxtonDeHate) [reply mp/src/game/shared/gamemovement.cpp]: I've never seen this, I like it.

File: mp/src/game/shared/gamemovement.cpp (hunk 4 above)
Comment (Gocnak) [reply mp/src/game/shared/gamemovement.cpp]: Yes. We're not Valve so we can start to do our own bits, even in SDK code.
