### PR TITLE
Prevented spectator mode & player changes while map finished or lobby members panel is open

### LINKED ISSUE #648: Right click to enable mouse on map finish & lobby panel executes the command bound to mouse2
Reported by 879m

**Describe the bug**
When in spectate, the right click to enable mouse feature on the map finished and lobby members panel doesn't eat the spectate input (`+attack`, `+attack2`, `+jump` to spectate next player, spectate previous player, and change spectator mode respectively). That is, the spectate command bound to `mouse2` is executed as well.

**To Reproduce**
Map finished panel:

1. Play a replay of a run.
2. Skip to end,
3. When map finished panel pops up, press right click to enable the mouse.
4. The spectate command bound to `mouse2` executes (eg. if `mouse2` bound to `+jump`, view will jump to thirdperson).

Lobby panel:

1. Spectate a player.
2. Press whatever is bound to `+duck` to disable mouse input.
3. Open the lobby members panel.
4. Press right click to enable mouse input.
5. The spectate command bound to `mouse2` executes.

**Expected behavior**
These panels should eat the spectate input. 

**Desktop (please complete the following information):**
 - OS: Windows

### PR DESCRIPTION
**Pull request by braem**
Closes #648 

Prevented spectator mode & player changes while map finished or lobby members panel is open. This prevents the spec command bound to `mouse2` (either `+attack`, `+attack2`, or `+jump`) from executing when enabling mouse input via right click on these panels.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/clientmode_mom_normal.cpp [hunk 1]
```diff
@@ -239,19 +239,19 @@ int ClientModeMOMNormal::HandleSpectatorKeyInput(int down, ButtonCode_t keynum,
...
         }
-        else if (down && pszCurrentBinding && !Q_strcmp(pszCurrentBinding, "+attack2") &&
-                 !m_pSpectatorGUI->IsMouseInputEnabled())
+        else if (down && pszCurrentBinding && !Q_strcmp(pszCurrentBinding, "+attack2") && !shouldEatSpecInput)
         {
             engine->ClientCmd("spec_prev");
             return 0;
         }
-        else if (down && pszCurrentBinding && !Q_strcmp(pszCurrentBinding, "+jump"))
+        else if (down && pszCurrentBinding && !Q_strcmp(pszCurrentBinding, "+jump") && !shouldEatSpecInput)
```
Comment (Gocnak) [inline mp/src/game/client/momentum/clientmode_mom_normal.cpp:254]: Use `FStrEq` instead for these:
```suggestion
        else if (down && pszCurrentBinding && FStrEq(pszCurrentBinding, "+jump") && !shouldEatSpecInput)
```
