### PR TITLE
Use the same tonemapping settings as CS:S

### LINKED ISSUE #752: HDR is more intense than it is in CS:S
**Describe the bug**
The HDR effects in Momentum Mod are noticeably brighter and more intense than it is in CS:S

**To Reproduce**
Run a map in CS:S with HDR and compare it to the same map with the same settings on Momentum Mod

**Expected behavior**
These settings should be the same as CS:S when the map has a tonemap controller and enforces settings like bloomscale.

**Comparison Videos**
surf_summer in momentum (2018)

[video link](https://youtu.be/ATbqQktjefs)

surf_summer in CS:S (2018)

[video link](https://youtu.be/TJj4lasVhhc)

**Desktop:**
 - OS: Windows / Linux

**Note:**
This inconsistency could possibly be with CS:S only and not other sdk 2013 games, more testing may be needed to see if TF2 varies as well.

### PR DESCRIPTION
**Pull request by xen-000**
Closes #752

CS:S uses a different version of dev/downsample_non_hdr and forced `mat_tonemap_algorithm 0`. By applying both changes, HDR bloom in momentum is now identical to that of CS:S.

Before:
image

After:
image

CS:S for scale:
image

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/viewpostprocess.cpp [hunk 1]
```diff
@@ -1502,11 +1502,11 @@ static void Generate8BitBloomTexture( IMatRenderContext *pRenderContext, float f
...
 	// Counter-Strike: Source uses a different downsample algorithm than other games
-	#ifdef CSTRIKE_DLL
+	//#ifdef CSTRIKE_DLL
 		IMaterial *downsample_mat = materials->FindMaterial( "dev/downsample_non_hdr_cstrike", TEXTURE_GROUP_OTHER, true);
-	#else
-		IMaterial *downsample_mat = materials->FindMaterial( "dev/downsample_non_hdr", TEXTURE_GROUP_OTHER, true);
-	#endif
+	//#else
+	//	IMaterial *downsample_mat = materials->FindMaterial( "dev/downsample_non_hdr", TEXTURE_GROUP_OTHER, true);
+	//#endif
```
Comment (Gocnak) [inline mp/src/game/client/viewpostprocess.cpp:1509]: We can remove the old code, we're on version control and can always see history of files.

Can we make that `downsample_non_hdr_cstrike` material instead be local? I have a feeling it's pulling it from the cstrike vpk and I'd like for it to be local, and we can even use the old name (`downsample_non_hdr`) for it. If I recall correctly it's just the `$cstrike 1` guy that makes the difference?

Comment (xen-000) [reply mp/src/game/client/viewpostprocess.cpp:1509]: The material is actually in the hl2 .vpks, oddly enough...
