### PR TITLE
Fix behaviour when exiting end zone with mapfinished panel open

### LINKED ISSUE #185: [Map Finished] trigger_momentum_timer_stop causing client to be stuck upon resetting
If the player has enough speed to pass thru the end trigger and exit on the other side he will be stuck upon resetting. 

https://www.youtube.com/watch?v=yO7W23uZbus

### PR DESCRIPTION
**Pull request by SlidyBat**
Exiting the end zone with the mapfinished panel still open will automatically close, leaving no opportunity for the user to look at it. This fixes that behaviour so that the mapfinished panel remains open until the player closes it or enters start zone by restarting.

Closes #185

### CODE REVIEW

File: mp/src/game/shared/momentum/run/mom_run_entity.cpp [hunk 1]
```diff
@@ -67,7 +67,6 @@ void CMomRunEntity::OnZoneExit(CTriggerZone *pTrigger)
         break;
     }
 
-    pData->m_bMapFinished = false;
```
Comment (Gocnak) [inline mp/src/game/shared/momentum/run/mom_run_entity.cpp]: Removing this negatively affects online/replay ghosts. Did you test playing back replays and restarting them? I would figure the panel would stay open for them with this change.

Perhaps moving this line to `OnZoneEnter`, specifically the `ZONE_TYPE_START` case would be good for all run entities. Then you can just keep the `SetLaggedMovement` call in the player and inheritance will set the `m_bMapFinished` bool to false for you.

Comment (SlidyBat) [reply mp/src/game/shared/momentum/run/mom_run_entity.cpp]: Removing it had no negative effect on replays since `m_bMapFinished` was set independently for replays, but I moved the common `m_bMapFinished = false` line to the base class anyway.

Comment (Gocnak) [reply mp/src/game/shared/momentum/run/mom_run_entity.cpp]: Resolved in fcd31e2
