### PR TITLE
Hardcode BurnLevel proxy to always be 0

### LINKED ISSUE #678: TF2 viewmodels have "burn" effects on them
**Describe the bug**
When using TF2 viewmodels, you can notice a slight burning effect on them. This is controlled by the BurnLevel proxy, and by default, the TF2 models appear to use the value of "0.01".

**To Reproduce**

1. Use the TF2 demoman sticky launcher
2. Notice the burning on the arm

**Expected behavior**
The [BurnLevel proxy code](https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/momentum/tf2proxy.cpp#L48) should be setting its value (`m_pResult->SetFloatValue(0.0f);` in the `Bind` void) to a hardcoded `0.0f` to counter this.

**Screenshots**
image
https://streamable.com/5so94u

**Desktop (please complete the following information):**
 - OS: Both

### PR DESCRIPTION
**Pull request by Hat-Kid**
This stops certain TF2 models from showing the burn texture.

Closes #678 

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/tf2proxy.cpp [hunk 1]
```diff
@@ -45,7 +45,20 @@ class CInvulnLevelProxy : public CResultProxy
...
+    void OnBind(void *pC_BaseEntity)
+    {
+        Assert(m_pResult);
+
+        if (!pC_BaseEntity)
+            return;
+
+        C_BaseEntity *pEntity = BindArgToEntity(pC_BaseEntity);
+        if (!pEntity)
+            return;
```
Comment (Gocnak) [inline mp/src/game/client/momentum/tf2proxy.cpp:57]: Is this needed? The entity isn't actually used in the OnBind function, do we need to cast it? I guess this also applies to the yellow level one too.

Comment (Hat-Kid) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: When I added the YellowLevel proxy, this was part of the code snippet ficool sent me, I thought I'd add these checks just in case it would cause issues otherwise, but if it's not needed, I can remove it from both proxies.

Comment (Gocnak) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: I would check if it's needed by removing it and seeing if it still works.

Comment (Hat-Kid) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: I am not able to check on Windows right now, but it appears that the game crashes without fail on Linux for me when I start an sj map with the TF2 sticky launcher model script, whether I keep the checks or not.

This is what is shown in the terminal at the time of the crash:
```
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 32 ps-combo 0
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 32 ps-combo 1
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 32 ps-combo 2
IDirect3DDevice9::CreatePixelShader: shaderapi's centroid mask (0x00000000) differs from mask derived from shader name (0x0000000C) for shader ps-file flashlight_ps20b ps-index 32 ps-combo 3
```

Comment (Gocnak) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: Does this happen on steam build too? Or just on this branch?

Comment (Hat-Kid) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: Only on this branch.

Comment (Gocnak) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: What about latest develop?

Comment (Hat-Kid) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: Latest develop works fine too.

The crash only happens as soon as I add `m_pResult->SetFloatValue(0.0f);` to the proxy.

Comment (Gocnak) [reply mp/src/game/client/momentum/tf2proxy.cpp:57]: Hmm. Maybe just `#ifdef` it out for now then. Weird that it's causing this, and yeah I'd fix this to be under the right proxy.

File: mp/src/game/client/momentum/tf2proxy.cpp [hunk 2]
```diff
@@ -35,7 +35,12 @@ class CBurnLevelProxy : public CResultProxy
...
   public:
     bool Init(IMaterial *pMaterial, KeyValues *pKeyValues) { return true; }
-    void OnBind(void *pC_BaseEntity) {}
+    void OnBind(void *pC_BaseEntity)
+    {
+#ifdef _WIN32
+        m_pResult->SetFloatValue(0.0f);
+#endif
+    }
     IMaterial *GetMaterial() { return nullptr; }
```
Comment (Gocnak) [inline mp/src/game/client/momentum/tf2proxy.cpp:44]: Upon testing this fix, windows gets a nullptr exception for the `m_pResult` pointer. Remove the `Init()` and `GetMaterial()` functions from this.
