### PR TITLE
Fix certain commands going through mapfinished panel

### LINKED ISSUE #1091: Some user inputs bypass map finish panel and go to game
**Describe the bug**
Player able to jump, crouch, and fire rocket launcher/sticky launcher while the "Map Finish" Panel is up

**To Reproduce**
- Enter start zone then finish zone
- Fire rocket launcher/ sticky launcher
- To allow crouching to bypass the panel, jump once with the panel up.
https://youtu.be/t6ev7vu9slY

**Expected behavior**
All user input to be taken by the panel rather than in-game (eg. No jumping, crouching, or rockets fired).

**Desktop/Branch (please complete the following information):**
 Windows - Steam 0.8.6

### PR DESCRIPTION
**Pull request by ijre**
Closes #1091 

This PR fixes specific commands going through the mapfinished panel even when `mom_mapfinished_movement_enable` is false.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/momentum/clientmode_mom_normal.cpp [hunk 1]
```diff
@@ -193,6 +193,10 @@ int ClientModeMOMNormal::HudElementKeyInput(int down, ButtonCode_t keynum, const
                 m_pSpectatorGUI->SetMouseInputEnabled(true);
             return 0;
         }
+
+        static ConVarRef mom_mapfinished_movement_enable("mom_mapfinished_movement_enable");
```
Comment (Gocnak) [inline mp/src/game/client/momentum/clientmode_mom_normal.cpp:197]: This convar is on the client project and can just be `extern`'d

**Review by Gocnak — CHANGES_REQUESTED** [review]

File: mp/src/game/client/momentum/clientmode_mom_normal.cpp (hunk 1 above)
Comment (ijre) [reply mp/src/game/client/momentum/clientmode_mom_normal.cpp:197]: Oh, I'm getting an error saying it's an unresolved extern, unsure if I'm missing something or misunderstanding you?

Comment (Gocnak) [reply mp/src/game/client/momentum/clientmode_mom_normal.cpp:197]: You may have to make it not static in the original file it's found in.

**Review by Gocnak — APPROVED** [review]
