### PR TITLE
Fix hud chat container not having mouse input

### LINKED ISSUE #1041: Cannot click on filter button or scroll on hud chat window (in-game)
**Describe the bug**
The hud chat's filter button and scrollbar cannot be clicked. Scrollbar doesn't scroll with mousewheel either. These work for the chat in the menu drawer.

**To Reproduce**
1. Load into a map
2. Open hud chat (`chat_open`)
3. Notice that filter button cannot be clicked
4. Spam chat to get the scrollbar to appear
5. Notice that you cannot click or mousewheel scroll the scrollbar.

**Expected behavior**
These should be interact-able

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch only

### PR DESCRIPTION
**Pull request by braem**
Closes #1041

The container was only getting mouse input when a lobby is made and the drawer's chat is clicked into. This adds `SetMouseInputEnabled(true)` calls to make the chat container and chat panel have mouse input when hud chat is opened. 

This doesn't happen with the drawers chat. I believe that's because the drawer already has mouse input. Not really sure what code makes mouse input enabled for the hud chat when the drawer's is clicked into though.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/client/hud_chat.cpp [hunk 1]
```diff
@@ -54,6 +54,7 @@ void CHudChat::StartMessageMode()
     SetKeyBoardInputEnabled(true);
 
     m_pChatContainer->StartMessageMode(MESSAGE_MODE_HUD);
+    m_pChatContainer->SetMouseInputEnabled(true);
```
Comment (Gocnak) [inline mp/src/game/client/hud_chat.cpp:57]: Something to test, would the container always having mouse input be better here? The HUD element having it takes mouse input away from the game, but would otherwise be the only thing needing toggled here.

Comment (braem) [reply mp/src/game/client/hud_chat.cpp]: Something like what I just pushed? Seems like it can always have mouse input from constructor and works just fine.

Comment (Gocnak) [reply mp/src/game/client/hud_chat.cpp]: Yes, so the other line can be removed too then?

Comment (braem) [reply mp/src/game/client/hud_chat.cpp]: It indeed can. Needed it before but not anymore with this change.

**Review by Gocnak — APPROVED** [review]
