### PR TITLE
Prevent give_weapon command in credits & main menu

### LINKED ISSUE #760: You can give yourself weapons while on the main menu
**Describe the bug**
Spamming `give_weapon` while on the main menu (loaded into the bg_01 map) drops them below the camera and can cause enough lag that the main menu becomes unusable, forcing you to alt+f4

**Expected behavior**
Spawning weapons or any entities at all while in the main menu should be prevented.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Funny bug, not necessarily game-breaking since who would think about doing that anyway, but still issue worthy.

### PR DESCRIPTION
**Pull request by braem**
Closes #760

Simple catch that prevents users from giving themselves weapons in the main menu/credits.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

File: mp/src/game/server/client.cpp [hunk 1]
```diff
@@ -906,6 +906,12 @@ CON_COMMAND_F_COMPLETION(give_weapon, "Gives the player a weapon.", 0, WeaponCom
 			return;
 		}
 
+        if (FStrEq(STRING(gpGlobals->mapname), "credits") || FStrEq(STRING(gpGlobals->mapname), "bg_00"))
```
Comment (Gocnak) [inline mp/src/game/server/client.cpp:909]:
```suggestion
        if (FStrEq(STRING(gpGlobals->mapname), "credits") || gpGlobals->eLoadType == MapLoad_Background)
```
